### ISSUE TITLE
write.csv() unable to write without dataframe column/row names

### ISSUE THREAD

**Issue by MandarinDuck** [moj-analytical-services/s3tools#37]
https://github.com/moj-analytical-services/s3tools/blob/18c4f2a6a7381824b0b683e0ae70959abda97867/R/write_to_s3.R#L14

**Comment by MandarinDuck** [comment]
If the line is replaced with `write.table(df, rc, sep= ",", ...)`, that ought to do it.

**Comment by MandarinDuck** [comment]
But making it more general and allowing users to optionally pass a separator argument would be better (although the function name would then be misleading).

**Comment by calumabarnett** [comment]
Implemented new `write_df_to_table_in_s3` function in 7297ee8.
